/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./sync_fifo_p.v:1.1-54.10" *)
module sync_fifo(clk, rst, w_en, r_en, din, dout, full, empty);
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [4:0] _00_;
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [31:0] _01_;
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [31:0] _02_;
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [4:0] _03_;
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [31:0] _04_;
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  wire [31:0] _05_;
  (* src = "./sync_fifo_p.v:35.18-35.23" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _06_;
  (* src = "./sync_fifo_p.v:51.18-51.23" *)
  (* unused_bits = "6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _07_;
  (* src = "./sync_fifo_p.v:22.20-22.67" *)
  wire _08_;
  (* src = "./sync_fifo_p.v:32.17-32.30" *)
  wire _09_;
  (* src = "./sync_fifo_p.v:48.17-48.31" *)
  wire _10_;
  (* src = "./sync_fifo_p.v:32.25-32.30" *)
  wire _11_;
  (* src = "./sync_fifo_p.v:48.25-48.31" *)
  wire _12_;
  (* src = "./sync_fifo_p.v:50.21-50.24" *)
  wire [31:0] _13_;
  (* src = "./sync_fifo_p.v:22.73-22.109" *)
  wire _14_;
  (* src = "./sync_fifo_p.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "./sync_fifo_p.v:7.24-7.27" *)
  input [31:0] din;
  wire [31:0] din;
  (* src = "./sync_fifo_p.v:8.30-8.34" *)
  output [31:0] dout;
  reg [31:0] dout;
  (* src = "./sync_fifo_p.v:9.18-9.23" *)
  output empty;
  wire empty;
  (* src = "./sync_fifo_p.v:9.12-9.16" *)
  output full;
  wire full;
  (* src = "./sync_fifo_p.v:17.26-17.27" *)
  reg [5:0] i;
  (* src = "./sync_fifo_p.v:17.28-17.29" *)
  reg [5:0] j;
  (* src = "./sync_fifo_p.v:6.27-6.31" *)
  input r_en;
  wire r_en;
  (* src = "./sync_fifo_p.v:6.16-6.19" *)
  input rst;
  wire rst;
  (* src = "./sync_fifo_p.v:6.21-6.25" *)
  input w_en;
  wire w_en;
  (* src = "./sync_fifo_p.v:13.23-13.26" *)
  reg [31:0] mem [31:0];
  always @(posedge clk) begin
    if (_02_[31])
      mem[_00_] <= _01_;
  end
  assign _13_ = mem[j[4:0]];
  assign _06_ = i + (* src = "./sync_fifo_p.v:35.18-35.23" *) 32'd1;
  assign _07_ = j + (* src = "./sync_fifo_p.v:51.18-51.23" *) 32'd1;
  (* src = "./sync_fifo_p.v:41.5-53.8" *)
  always @(posedge clk)
    if (rst) dout <= 32'd0;
    else if (_10_) dout <= _13_;
  (* src = "./sync_fifo_p.v:41.5-53.8" *)
  always @(posedge clk)
    if (rst) j <= 6'h00;
    else if (_10_) j <= _07_[5:0];
  (* src = "./sync_fifo_p.v:26.5-37.8" *)
  always @(posedge clk)
    if (rst) i <= 6'h00;
    else if (_09_) i <= _06_[5:0];
  assign empty = i == (* src = "./sync_fifo_p.v:21.21-21.27" *) j;
  assign _08_ = i[4:0] == (* src = "./sync_fifo_p.v:22.20-22.67" *) j[4:0];
  assign full = _08_ && (* src = "./sync_fifo_p.v:22.19-22.110" *) _14_;
  assign _09_ = w_en && (* src = "./sync_fifo_p.v:32.17-32.30" *) _11_;
  assign _10_ = r_en && (* src = "./sync_fifo_p.v:48.17-48.31" *) _12_;
  assign _11_ = ! (* src = "./sync_fifo_p.v:32.25-32.30" *) full;
  assign _12_ = ! (* src = "./sync_fifo_p.v:48.25-48.31" *) empty;
  assign _14_ = i[5] != (* src = "./sync_fifo_p.v:22.73-22.109" *) j[5];
  assign _05_[31] = _09_ ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:32.17-32.30|./sync_fifo_p.v:32.14-36.12" *) 1'h1 : 1'h0;
  assign _04_ = _09_ ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:32.17-32.30|./sync_fifo_p.v:32.14-36.12" *) din : 32'hxxxxxxxx;
  assign _03_ = _09_ ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:32.17-32.30|./sync_fifo_p.v:32.14-36.12" *) i[4:0] : 5'hxx;
  assign _02_[31] = rst ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:28.12-28.15|./sync_fifo_p.v:28.9-36.12" *) 1'h0 : _05_[31];
  assign _01_ = rst ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:28.12-28.15|./sync_fifo_p.v:28.9-36.12" *) 32'hxxxxxxxx : _04_;
  assign _00_ = rst ? (* full_case = 32'd1 *) (* src = "./sync_fifo_p.v:28.12-28.15|./sync_fifo_p.v:28.9-36.12" *) 5'hxx : _03_;
  assign _02_[30:0] = { _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31] };
  assign _05_[30:0] = { _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31], _05_[31] };
endmodule
